#!/bin/sh
# [K]2022
# https://github.com/kongfl888

C=/tmp/adupdate_dnsfilter.log
D="date +'%Y-%m-%d %H:%M:%S'"

echo "`eval $D` [Check Subscribe Rules Update]" >> $C

/usr/share/dnsfilter/addown --down 1 >/dev/null 2>&1

echo "`eval $D` [Reload Rules]" >> $C
/etc/init.d/dnsmasq restart >/dev/null 2>&1

exit 0
