#!/bin/sh
# [K]2022
# https://github.com/kongfl888

grep -E "^address=\/\S+\.\S+\/((\d{1,3}\.){3}\d{1,3}){0,1}$" $1 > /tmp/ad_check.txt
R=$?
if [ "$R" = "0" ];then
	echo "`sort -u /tmp/ad_check.txt`" > /tmp/ad_check.txt
	cp -f /tmp/ad_check.txt $1
	rm -f /tmp/ad_check.txt
fi
