#!/bin/sh
# [K]2022
# https://github.com/kongfl888

grep -oE "^address=\/\S+\.\S+[0-9a-zA-Z]\/(([0-9]+\.){3}[0-9]+(#[0-9]+)?)?" $1 > /tmp/ad_check.txt
R=$?
if [ "$R" = "0" ];then
	echo "`sort -u /tmp/ad_check.txt`" > /tmp/ad_check.txt
	cp -f /tmp/ad_check.txt $1
	rm -f /tmp/ad_check.txt
fi
