#!/bin/sh
# [K]2022
# https://github.com/kongfl888

Logfile="/tmp/adupdate_dnsfilter.log"

T=`dnsmasq --test 2>&1 | grep "OK" -c`
B=baidu.com
Q=qq.com
DC=0

D=`ping -c 1 $B 2>&1 | grep 'bad' -c`
C="ping -c 1 $Q 2>&1 | grep 'bad' -c"
[ $D -gt 0 ] && DC=`eval $C`

if [ $T -eq 0 -o $DC -gt 0 ]; then
	exit 1
else
	exit 0
fi
